### PR TITLE
Changed the Ubuntu VM Image name.

### PR DESCRIPTION
**Pull request by NiklasGustafsson**

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
Attempts to update the Linux version didn't help.

**Comment by dsyme** [comment]
Just to mention building the Linux bits on 16.0 container or image is necessary (we could use a 16.0 container on a 20.04 image).

This is because the Linux C++ build process picks up a dependency on the C++ runtime of the system its built on. By building on 16.0 we can run in many different Linux systems including those found in Google CoLab notebooks for example.

**Comment by dsyme** [comment]
> Attempts to update the Linux version didn't help.

Is there something that needs this?  thanks

**Comment by NiklasGustafsson** [comment]
@dsyme -- got it. The Linux builds have been failing since Thursday, with some error like this:

```
2021-10-04T11:32:11.7390375Z Ign:12 https://apt.kitware.com/ubuntu xenial/main amd64 Packages
2021-10-04T11:32:11.8423878Z Ign:10 https://apt.kitware.com/ubuntu xenial/main all Packages
2021-10-04T11:32:11.9508173Z Ign:12 https://apt.kitware.com/ubuntu xenial/main amd64 Packages
2021-10-04T11:32:12.0624603Z Ign:10 https://apt.kitware.com/ubuntu xenial/main all Packages
2021-10-04T11:32:12.1651045Z Err:12 https://apt.kitware.com/ubuntu xenial/main amd64 Packages
2021-10-04T11:32:12.1652653Z   server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
2021-10-04T11:32:12.1780934Z Fetched 7,489 kB in 1s (4,387 kB/s)
```
This is while building the environment that is later used to do the actual build. Before the task gets to the TorchSharp sources, in other words.

I have been unable to figure out what is going on, and I was hoping that this was something that the people behind 'apt.kitware.com' would found and fixed. The version change was a desperation move.

**Pull request closed without merging**
