### PR TITLE
Added to always initialize CUDA 

### PR DESCRIPTION
**Pull request by shaltielshmid**
Fixes https://github.com/dotnet/TorchSharp/issues/1198.

I tested it out locally - I added the DLL and the libtorch-cuda package, and it worked. I then tried it with the libtorch-cpu package and I confirmed that it didn't crash. 

I was going to add a test for it - but in our CUDA tests we always check that cuda is available, and then that defeats the purpose since checking if it is available initializes it. 
Do you have any suggestions?

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
> Fixes #1198.
> 
> I tested it out locally - I added the DLL and the libtorch-cuda package, and it worked. I then tried it with the libtorch-cpu package and I confirmed that it didn't crash.
> 
> I was going to add a test for it - but in our CUDA tests we always check that cuda is available, and then that defeats the purpose since checking if it is available initializes it. Do you have any suggestions?

Suggestions on how to testing for a failure of a failure-safe thing? :-)

**Comment by shaltielshmid** [comment]
Was just about to write about that :)

**Comment by shaltielshmid** [comment]
Okay, so there are two questions:

1] How do we test for this bug? Even if I add another cuda-only test file, there is no guarantee that that test will run before a different test which calls a cuda function and loads the binaries in. Do we wan to skip?

2] This silent bug - if someone uses torch.CUDA when initializing a tensor when cuda isn't available, then TorchSharp will just skip over it and load it into CPU. Is this behavior OK? If not, we should probably just implement it as a static initializer or as a different static field (we can have a private static field that isn't used `private static bool initCudaIsAvailable = torch.cuda.is_available();`).

**Comment by shaltielshmid** [comment]
> Suggestions on how to testing for a failure of a failure-safe thing? :-)

Lol. Test locally? ;-)

**Comment by NiklasGustafsson** [comment]
> Okay, so there are two questions:
> 
> 1] How do we test for this bug? Even if I add another cuda-only test file, there is no guarantee that that test will run before a different test which calls a cuda function and loads the binaries in. Do we wan to skip?
> 
> 2] This silent bug - if someone uses torch.CUDA when initializing a tensor when cuda isn't available, then TorchSharp will just skip over it and load it into CPU. Is this behavior OK? If not, we should probably just implement it as a static initializer or as a different static field (we can have a private static field that isn't used `private static bool initCudaIsAvailable = torch.cuda.is_available();`).

Yes, I think the static initializer should work.

**Comment by shaltielshmid** [comment]
So as it turns out, torch already had a static initializer :)
I just added the initialize call to the initializer.

**Comment by NiklasGustafsson** [comment]
Looks good, except the CUDA field is still not readonly.

**Comment by shaltielshmid** [comment]
The CUDA is not a field :-)

**Comment by NiklasGustafsson** [comment]
> torch.CUDA is not a field :-) I had initially made it a field - but then I reverted back

Reason? I thought that's what you wanted it to be?

**Comment by shaltielshmid** [comment]
I did - and that had solved the issue. But the problem was that when we made it a field the following code no longer crashed:
```cs
var t = torch.rand(10, device: torch.CUDA);
```

(This was actually taken from a test)

**Comment by shaltielshmid** [comment]
The issue is that this can cause silent crashes when previous it didn't. See for example the test over here: https://github.com/dotnet/TorchSharp/blob/main/test/TorchSharpTest/TestTorchTensor.cs#L3758

The question is whether silent handling is the way to go. Since when it isn't available we replace it with null which is a valid parameter to pass when creating a tensor (that just means the default device = cpu)

**Comment by NiklasGustafsson** [comment]
Since it is a property, I think the result needs to be memoized (a problem that was present before your PR, too).

**Comment by shaltielshmid** [comment]
Sure, added memoization now.

**Comment by NiklasGustafsson** [comment]
> Sure, added memoization now.

Waiting for the build to finish, and then I'll merge.

**Pull request merged**
