### PR TITLE
Added some CUDA and CUDNN backend properties.

### PR DESCRIPTION
**Pull request by NiklasGustafsson**
Adding some backend properties, per issue #889.

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
@dje-dev, please take a look at this PR.

**Comment by dje-dev** [comment]
Thank you for the quick enhancement. Looks good. The only suggestion is to consider carrying forward the distinction of using "cublas" in some of the names (as you already do with "cudnn") rather than referring to them generically as "cuda".

**Comment by NiklasGustafsson** [comment]
> Thank you for the quick enhancement. Looks good. The only suggestion is to consider carrying forward the distinction of using "cublas" in some of the names (as you already do with "cudnn") rather than referring to them generically as "cuda".

The intent was to follow the Pytorch namespace hierarchy.

**Comment by dje-dev** [comment]
In numerous places, including the DLLExport method signatures but also in the C++ shown here, the underlying name has "CuBLAS" rather than the more generic "cuda" so it seemed a more directly translation to use "cublas."
void THSBackend_cuda_set_allow_tf32(const bool flag)
 {
     CATCH(at::globalContext().setAllowTF32CuBLAS(flag););
 }

**Comment by NiklasGustafsson** [comment]
> In numerous places, including the DLLExport method signatures but also in the C++ shown here, the underlying name has "CuBLAS" rather than the more generic "cuda" so it seemed a more directly translation to use "cublas." void THSBackend_cuda_set_allow_tf32(const bool flag) { CATCH(at::globalContext().setAllowTF32CuBLAS(flag);); }

Got it. I don't generally spend a lot of time on the interop names, but it's a fair point.

**Pull request merged**
