### PR TITLE
Added inference mode context manager

### PR DESCRIPTION
**Pull request by shaltielshmid**
Added support for torch.inference_mode() context manager, for faster evaluation.
In which should file should I add a unit test?

Also, does it make sense for a unit test where I enabled inference_mode, and then call torch.is_inference_mode_enabled() to confirm?

### CODE REVIEW

**Review by NiklasGustafsson — COMMENTED** [review]
There must be some new unit tests when adding new functionality.

**Comment by NiklasGustafsson** [comment]
@shaltielshmid -- for all your PRs, please add appropriate language to RELEASENOTES.md.

**Comment by shaltielshmid** [comment]
Added unit tests.

Sure, what version should I add?

**Comment by NiklasGustafsson** [comment]
> Added unit tests.
> 
> Sure, what version should I add?

It'll be 0.101.3, and please edit `build/BranchInfo.props` while you're at it.

Thanks,

Niklas

**Comment by shaltielshmid** [comment]
Done. 
I'll wait for this branch to be merged, and then I'll update the release notes on the rest of the branches as to not create merge conflicts.

**Comment by NiklasGustafsson** [comment]
> Done. I'll wait for this branch to be merged, and then I'll update the release notes on the rest of the branches as to not create merge conflicts.

Okay. I'll merge some of the simpler PRs first.

**Comment by shaltielshmid** [comment]
The mode is only for the given context and doesn't apply to other tasks and threads. I ran this code to confirm:

```cs

            Task.Run(() => {
                while (true) {
                    Console.WriteLine("Background thread before activation: " + torch.is_inference_mode_enabled());
                    Thread.Sleep(500);
                }
            });

            // Let it run for 2 seconds
            Thread.Sleep(2000);

            // Activate inference mode
            Console.WriteLine("Foreground thread before activation: " + torch.is_inference_mode_enabled());
            using var d = torch.inference_mode();
            Console.WriteLine("Foreground thread after activation: " + torch.is_inference_mode_enabled());

            Task.Run(() => {
                while (true) {
                    Console.WriteLine("Background thread after activation: " + torch.is_inference_mode_enabled());
                    Thread.Sleep(500);
                }
            });

            // Let it run for another 2 seconds to confirm inference mode is still false in the other context.
            Thread.Sleep(2000);

            Console.WriteLine("Foreground thread after activation: " + torch.is_inference_mode_enabled());
```

The output was:
```
Background thread before activation: False
Background thread before activation: False
Background thread before activation: False
Background thread before activation: False
Foreground thread before activation: False
Foreground thread after activation: True
Background thread after activation: False
Background thread before activation: False
Background thread after activation: False
Background thread before activation: False
Background thread after activation: False
Background thread before activation: False
Background thread after activation: False
Background thread before activation: False
Foreground thread after activation: True
```

**Comment by shaltielshmid** [comment]
I also tried calculating gradients in each of the contexts, and an error was thrown only in the main context.

**Review by NiklasGustafsson — APPROVED** [review]

**Pull request merged**
