### PR TITLE
Added state index ref to optimizer state dict

### PR DESCRIPTION
**Pull request by shaltielshmid**
While adding the functionality for saving the optimizer state_dict in the pytorch format, I encountered an issue that I couldn't resolve externally. 

When looking at an optimizer state_dict in Python, they have an index mapping between the parameter_group and the state group. 

E.g., see here a sample state_dict of an Adam optimizer:

```json
{
  "state": {
      0: {
        "step": tensor(1.),
        "exp_avg": tensor(...),
        "exp_avg_seq": tensor(...)
      },
      1: {
        "step": tensor(1.),
        "exp_avg": tensor(...),
        "exp_avg_seq": tensor(...)
      },
   },
  "param_groups": [
    {
      "lr": 0.001,
      "betas": [
        0.8,
        0.9
      ],
      "eps": 1e-08,
      "weight_decay": 0,
      "amsgrad": false,
      "maximize": false,
      "foreach": null,
      "capturable": false,
      "differentiable": false,
      "fused": null,
      "params": [
        0,
        1
      ]
    }
  ]
}
```

For TorchSharp, there is no need for the params, but PyTorch requires the Params object which maps between the params and the states to be included. 

Therefore, I propose this addition which will include the mapping between parameters the state, without inserting any breaking changes.

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
Since you're digging around (deep) in this -- would you mind attacking #1153 while you're at it?

**Comment by shaltielshmid** [comment]
Sure! I think this relates directly to what I emailed you about on Thursday, figuring out a way to reinitialize a state dynamically.

**Comment by shaltielshmid** [comment]
Yes! Working on that + Release notes.

**Comment by shaltielshmid** [comment]
@NiklasGustafsson done - I added a check in `exportsd.py` and updated the release notes.

**Review by NiklasGustafsson — APPROVED** [review]

**Pull request merged**
