### PR TITLE
Added SpeechCommands example

### PR DESCRIPTION
**Pull request by kaiidams**
This model achieves around 60-70% accuracy which is similar to PyTorch version. However, it depends on `torchaudio.transform.Resample()` which is not available in TorchSharp yet.

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
@kaiidams -- I merged the Resample PR, so if that means that this is no longer "WIP," then let me know and I'll do a review.

**Comment by NiklasGustafsson** [comment]
@kaiidams -- what are the system requirements for running the example on a GPU? Does it fit in 8GB of memory? That's been our general guideline for examples, to be able to run in a consumer-grade GPU.

**Comment by NiklasGustafsson** [comment]
@kaiidams -- sorry, I wasn't sure if you wanted to remove the "WIP" designation, but it seemed like you had done the change that you were blocked on. Please let me know if you want me to merge.

**Comment by kaiidams** [comment]
> @kaiidams -- what are the system requirements for running the example on a GPU? Does it fit in 8GB of memory? That's been our general guideline for examples, to be able to run in a consumer-grade GPU.

@NiklasGustafsson This runs with CPU with 8GB RAM, though I haven't tested with GPU.

**Comment by NiklasGustafsson** [comment]
@kaiidams -- so, should I merge, or is this still work in progress?

**Review by NiklasGustafsson — APPROVED** [review]

**Pull request merged**
