### PR TITLE
Add combo packages

### PR DESCRIPTION
**Pull request by dsyme**
This adds one-stop packages that combine TorchSharp with an appropriate backend

* `TorchSharp-cpu` (CPU)

* `TorchSharp-cuda-linux` (CPU)

* `TorchSharp-cuda-windows` (CPU)

This lets people reference just `TorchSharp-cpu` for example and everything should work with right versions - they don't need to know which version of CUDA or libtorch is being used, nor see "x64", nor even know the libtorch packages exist. The CUDA version and architecture is left implied ro "latest supported by TorchSharp".   This is good for longevity of samples

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
@dsyme -- This is in addition to the existing packages, right?

**Comment by dsyme** [comment]
> @dsyme -- This is in addition to the existing packages, right?



Yes

**Comment by NiklasGustafsson** [comment]
Does the Azure-pipelines YAML file need any updating for these packages?

**Comment by dsyme** [comment]
@NiklasGustafsson Yes it will, I'll think about that

See https://github.com/dotnet/TorchSharp/issues/348 also

**Comment by NiklasGustafsson** [comment]
@dsyme I think your changes to the README file are a little confusing. 

Should I use TorchSharp-XXX, or TorchSharp + libtorch-XXX? Is that my choice, or does this new package structure replace the old manual combos? I'm not sure the text makes that clear.

**Comment by dsyme** [comment]
@NiklasGustafsson On the naming, I think we should go for the simpler names:

* `TorchSharp-cpu`

* `TorchSharp-cuda-linux`

* `TorchSharp-cuda-windows`

That is a typical notebook will just have

```fsharp
#r "nuget: TorchSharp-cuda-linux"
```

and you'll get 64-bit Linux CUDA for whatever cuda version is the latest supported by TorchSharp.

**Comment by NiklasGustafsson** [comment]
Not supporting CUDA 10.2 will make some people unhappy, so we need to cover that in the README.

**Comment by gbaydin** [comment]
Do I understand it correctly that `TorchSharp`, `TorchSharp-cpu`, `TorchSharp-cuda-linux`, `TorchSharp-cuda-windows` are guaranteed to share the same version number in each new release?

**Comment by NiklasGustafsson** [comment]
Yes. The build script builds all of them, and the script to push to NuGet pushes them all, so they should be in sync. The latter three are actually empty, they just contain the signature and references to TorchSharp and the right libtorch-xxx backend library. Right now, that is 0.93.5, which contains an important bug fix to how Data<T>() (also renamed 'data<T>()' in the same release) was implemented.

The libtorch-xxx packages, on the other hand, will continue to have version numbers based on the release from Pytorch.org that they wrap.

**Pull request merged**
