### PR TITLE
Modules -- a more complete implementation.

### PR DESCRIPTION
**Pull request by NiklasGustafsson**
Adding {Module|Parameter}{List|Dict}

### CODE REVIEW

**Comment by dsyme** [comment]
I've only looked through on my phone but it all looks good. I'll mark as approved - if you'd like me to do a line by line review I could do that tomorrow or next week

**Comment by NiklasGustafsson** [comment]
> I've only looked through on my phone but it all looks good. I'll mark as approved - if you'd like me to do a line by line review I could do that tomorrow or next week

No need. It's pretty straight-forward.

**Review by dsyme — APPROVED** [review]

**Comment by pkese** [comment]
@NiklasGustafsson I went through the text and it is wonderful.

The only thing I had trouble with is in the first example,
```csharp
public TestModule1(Tensor tensor, bool withGrad)
```
... where the `tensor` parameter is never used so I spent some time figuring out what it is doing there.

I assume it is a static parameter which becomes useful in a Sequential definition, but in this particular case it's just a distraction to the reader since it is unused. Maybe it would be a better idea to explain the tensor-as-a-module-parameter concept separately and omit it in the first example.

**Comment by NiklasGustafsson** [comment]
@pkese -- thanks for pointing that out. That argument should not be there at all. I'll remove it.

**Pull request merged**
