### PR TITLE
Add new test fixtures to CudaBinaries project resolves #1394

### LINKED ISSUE #1394: New contributor didn't link tests in WithCudaBinaries project

### PR DESCRIPTION
**Pull request by mvphelps**
Fixed, thanks @NiklasGustafsson I'll remember this in the future. I assume no need to update release notes on this one.

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
Merged and released.

**Comment by mvphelps** [comment]
@NiklasGustafsson does that mean I should see it on nuget.org? I don't see it, and readme still shows v0.103.0. Also the latest build looks like it did complete the native build but skipped cuda packaging, and didn't push packages: https://dotnet.visualstudio.com/TorchSharp/_build/results?buildId=110856&view=results

**Comment by NiklasGustafsson** [comment]
Once it's indexed by NuGet.

**Comment by mvphelps** [comment]
Ok that's the patience thing I'm working on. Got it. I'll check tomorrow!

**Comment by NiklasGustafsson** [comment]
> Ok that's the patience thing I'm working on. Got it. I'll check tomorrow!

Not that long. Give it another 20-30 minutes.

**Comment by NiklasGustafsson** [comment]
Aha! Certificate problem holding it up...

**Comment by NiklasGustafsson** [comment]
Available on NuGet now.

**Comment by mvphelps** [comment]
@NiklasGustafsson 
1. Am now using the new scope changes with packed sequences. Working great!
2. I appreciate your quick responses and good code review feedback. Being the PR guy can be thankless sometimes, so THANK YOU!

**Comment by NiklasGustafsson** [comment]
It's the opposite of thankless when community members send PRs my way... :-)

**Pull request merged**
