### PR TITLE
[Draft] Lighten Tensor.Factories file

### PR DESCRIPTION
**Pull request by ChengYen-Tang**
I found that torchsharp has many files that are too large, making it difficult to read and maintain
So, I will first split a file, and discuss
@NiklasGustafsson, Do you have any suggestions?

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
Let's change this one to 'draft' and discuss... I want to try to get a release out today, if possible and if we can get @GilesBathgate's two remaining PRs merged. The irregular build problems are slowing things down, but let's revisit this after the release.

**Comment by GilesBathgate** [comment]
> @GilesBathgate's two remaining PRs merged. The irregular build problems are slowing things down, but let's revisit this after the release.

`save_image/make_grid` pushes coming. RandAugment needs more work for unit tests/docs. Should be done over w/end hopefully.

**Comment by NiklasGustafsson** [comment]
> > @GilesBathgate's two remaining PRs merged. The irregular build problems are slowing things down, but let's revisit this after the release.
> 
> `save_image/make_grid` pushes coming. RandAugment needs more work for unit tests/docs. Should be done over w/end hopefully.

Okay. We'll hold the release off until next week, then. Thanks for your contributions!

**Comment by ChengYen-Tang** [comment]
@NiklasGustafsson,
I observed the two PRs of @GilesBathgate, and it seems that they are not directly related to this PR.
https://github.com/dotnet/TorchSharp/pull/1053/files
https://github.com/dotnet/TorchSharp/pull/1052/files

**Comment by NiklasGustafsson** [comment]
> @NiklasGustafsson, I observed the two PRs of @GilesBathgate, and it seems that they are not directly related to this PR. https://github.com/dotnet/TorchSharp/pull/1053/files https://github.com/dotnet/TorchSharp/pull/1052/files

I agree. However, babysitting intermittently failing builds is taking a lot of time :-(, so I would like to delay this PR, which is a source organization PR, not anything of functional significance such as bug fixes or new APIs.

**Comment by GilesBathgate** [comment]
@NiklasGustafsson @ChengYen-Tang Please don't put anything on hold / draft on my behalf.

**Comment by ChengYen-Tang** [comment]
Hope that before this draft is finalized, there will be no PR to change Tensor.Factories.cs
Because, I moved the location of Tensor.Factories.cs. So, merging and tracking changes is a bit cumbersome.

**Comment by NiklasGustafsson** [comment]
> Hope that before this draft is finalized, there will be no PR to change Tensor.Factories.cs Because, I moved the location of Tensor.Factories.cs. So, merging and tracking changes is a bit cumbersome.

:-) Extremely unlikely. That's a very stable file...

**Comment by NiklasGustafsson** [comment]
> @NiklasGustafsson @ChengYen-Tang Please don't put anything on hold / draft on my behalf.

It's not... it's on _my_ behalf.... :-) 

Restructuring source code will be a great thing to do once we have this release out.

**Comment by NiklasGustafsson** [comment]
> > Hope that before this draft is finalized, there will be no PR to change Tensor.Factories.cs Because, I moved the location of Tensor.Factories.cs. So, merging and tracking changes is a bit cumbersome.
> 
> :-) Extremely unlikely. That's a very stable file...

By which I mean that there are very rarely any changes to it. Very static, so the risk of merge conflicts are minimal. I'll cut the release after @GilesBathgate's two PRs are in and will put off everything else until after it.

**Comment by ChengYen-Tang** [comment]
That's great.
Many profiles should lose weight, they are not good looking and not healthy.🤣

**Comment by NiklasGustafsson** [comment]
There were no merge issues, as I suspected.

**Pull request merged**
