### PR TITLE
Add `torchvision.models.mobilenet_v3_large()` and torchvision.models.mobilenet_v3_small()`

### PR DESCRIPTION
**Pull request by kaiidams**
https://github.com/dotnet/TorchSharp/issues/588 State-dict compatible with 

- https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth
- https://download.pytorch.org/models/mobilenet_v3_large-5c1a4163.pth
- https://download.pytorch.org/models/mobilenet_v3_large-8738ca79.pth

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
@kaiidams 

Thank you for keep sharing **modules** that are compatible with loading state dictionaries from trained models in .pth format.

So far, the unit tests only unit test the modules and not the extraction of state dictionaries from the trained models. (Am I wrong?)

Perhaps this could be done through the Torchsharp Examples as console apps?

**Comment by kaiidams** [comment]
@GeorgeS2019 This is the same as other TorchSharpVision models like ResNet. It provides code which can consume pretrained models converted from official PyTorch models. We aren't using any pre-trained models in this repository. The unit test just checks the numbers of parameters and make sure they don't crash.

`TorchSharpExamples` provides simplified ResNet and MobileNet, which are smaller versions and are not compatible with the official models. It trains the model itself with CIFAR-10 dataset from scratch. Usually MobileNet is pre-trained with ImageNet.

**Comment by GeorgeS2019** [comment]
> We aren't using any pre-trained models

These are pre-trained models? Right?

- https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth
- https://download.pytorch.org/models/mobilenet_v3_large-5c1a4163.pth
- https://download.pytorch.org/models/mobilenet_v3_large-8738ca79.pth

**Comment by kaiidams** [comment]
Yes, they are official PyTorch pretrained models. They are compatible with `TorchSharpVision`.

**Comment by GeorgeS2019** [comment]
> Yes, they are official PyTorch pretrained models. They are compatible with TorchSharpVision.

Could you Please just point to to an example where State Dict are extracted from these pre-trained models?

Do you have exaamples too for TorchAudio?

**Comment by kaiidams** [comment]
@GeorgeS2019 This download a state dict from PyTorch and converts it.

```python
import os
import torch
import exportsd

url = 'https://download.pytorch.org/models/mobilenet_v2-7ebf99e0.pth'
url = 'https://download.pytorch.org/models/mobilenet_v2-b0353104.pth'
url = 'https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth'
url = 'https://download.pytorch.org/models/mobilenet_v3_large-5c1a4163.pth'
url = 'https://download.pytorch.org/models/mobilenet_v3_large-8738ca79.pth'

state = torch.hub.load_state_dict_from_url(
	url=url,
	progress=True)
fname = os.path.basename(url).replace('.pth', '.bin')
with open(fname, 'wb') as fp:
	exportsd.save_state_dict(state, fp)
```

**Comment by GeorgeS2019** [comment]
So we do not have a c# solution to extract state dict from url.

What would you like to recommend for the file extension of exported state dicts from python codes for ingestion using Torchsharp?

Currently, Torchsharp has no DIRECT way to work on pre-trained PyTorch Models ( .pth), but through an intermediate python code.

Do you have idea how to improve this situation?

**Comment by kaiidams** [comment]
@GeorgeS2019 JFYI, developers usually need a sample which is closer to real scenarios like this. The sample use pre-trained Tensorflow model with their dataset.

https://github.com/dotnet/machinelearning-samples/tree/main/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow?WT.mc_id=dotnet-35129-website

**Comment by kaiidams** [comment]
> What would you like to recommend for the file extension of exported state dicts from python codes for ingestion using Torchsharp?

- https://github.com/dotnet/TorchSharp/issues/713 is about having TorchSharp's own repository to keep converted files.
- Or write more explanations

**Comment by GeorgeS2019** [comment]
I was thinking about .dotnet interactive notebook.

To allow a user to load pretrained PyTorch Model from url,  we currently could not support that in the notebook

**Comment by GeorgeS2019** [comment]
> keep converted files.

Totally agree, we need Converted Files.  Same as Rust binding to LibTorch

**Comment by kaiidams** [comment]
I think dotnet interactive can run both Python and C# in a single notebook.

**Comment by GeorgeS2019** [comment]
> I think dotnet interactive can run both Python and C# in a single notebook.
Need to check on that. Not sure

**Comment by GeorgeS2019** [comment]
https://github.com/dotnet/interactive/discussions/1893

**Comment by GeorgeS2019** [comment]
Rust binding of pre-trained PyTorch Models are now available and distributed through e.g. HuggingFace

**Comment by kaiidams** [comment]
@GeorgeS2019 https://github.com/dotnet/interactive/blob/main/docs/polyglot.md Sorry this was what I meant, but Python is not included. Maybe you can make two notebooks with Python and C#.

**Comment by GeorgeS2019** [comment]
> make two notebooks with Python and C#.

The closest to real-world experience is always **ONE** notebook

.net interactive current way to python and PyTorch is PythonNET.  I think python kernel for .interactive is WIProgress

**Comment by GeorgeS2019** [comment]
We need converted pre-trained models compatible for ingestion by TorchSharp directly. => As u have recommended and proposed.

**Comment by kaiidams** [comment]
dotnet interactive is one of kernel of Jupyter. Jupyter can run any Python notebooks which can do with Jupyter.
Just select Python kernel.

image

**Comment by GeorgeS2019** [comment]
Yes..u are right..

**Review by NiklasGustafsson — APPROVED** [review]

**Pull request merged**
