### PR TITLE
Added section in Save/Load readme for TorchSharp.PyBridge

### PR DESCRIPTION
**Pull request by shaltielshmid**
I added a paragraph in the Wiki referencing the package. 
Please let me know if you want me to revise it in any way.

### CODE REVIEW

**Review by NiklasGustafsson — APPROVED** [review]

**Comment by NiklasGustafsson** [comment]
Does PyBridge also support saving/loading optimizer state, or just modules?

**Comment by shaltielshmid** [comment]
Right now only Modules. I'm looking into loading Optimizer states. Would you like me to revisit this PR after I get it working with Optimizer states?

**Comment by NiklasGustafsson** [comment]
You should come back with a new PR for that, but please do so.

**Comment by shaltielshmid** [comment]
@NiklasGustafsson Thanks for adding it into the wiki! I think there was a slight mishap in the wiki and the markdown for the added section and the one after it only got partially rendered. See here:

image

**Comment by NiklasGustafsson** [comment]
Fixed

**Pull request merged**
