### PR TITLE
Fix Net docs

### PR DESCRIPTION
**Pull request by ekagra-ranjan**
* Replace "MobileNet" with "ResNet" for ResNet implementation's Doc.
* Remove Remarks for MobileNet and ResNet

Hi @NiklasGustafsson, I removed the remarks from these files because it looks to me that they were copied from the VGG file (based on this [commit](https://github.com/dotnet/TorchSharp/commit/bf29b30ea4cf9917b9bf70f9674b0b010672e93c)) which later got upated [here](https://github.com/dotnet/TorchSharp/commit/25d32343ee929b828ad1c678ca60768a4489dde8). Please let me know if you wish to keep the remark sections.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=378) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=378) before we can accept your contribution.<br/><br/>:x: ekagra-ranjan [sign now](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=378)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/TorchSharp?pullRequest=378) it.</sub>

**Comment by NiklasGustafsson** [comment]
Maybe we should remove that comment everywhere.

**Comment by NiklasGustafsson** [comment]
The comment was correct for MobileNet, but not ResNet.

**Comment by ekagra-ranjan** [comment]
@NiklasGustafsson done

**Comment by NiklasGustafsson** [comment]
@ekagra-ranjan -- thanks for your contribution. I will merge the PR now.

If you have more thoughts on the docs, or come up with examples to include, your contributions would be very welcome.

**Comment by ekagra-ranjan** [comment]
@NiklasGustafsson I am exploring the codebase as of now and definitely look forward to contributing to TorchSharp.

**Pull request merged**
