### PR TITLE
moving P/Invoke declarations into dedicated class

### PR DESCRIPTION
**Pull request by MovGP0**
In order to follow [Native interoperability best practices](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/best-practices), I've moved *P/Invoke declarations into in a class with the same name as the native library*.

### CODE REVIEW

**Comment by MovGP0** [comment]
**Notes**
- The new file is quite large. It might be useful to split it into smaller files. 
- The rendundancy of the various `HType` classes should also be resolved: 
  - `torch.nn.Module.HType`
  - `torch.jit.Type.HType`
  - `torch.nn.utils.rnn.PackedSequence.HType`
  - `torch.optim.Optimizer.HType`

**Comment by NiklasGustafsson** [comment]
@MovGP0 -- these errors appear on all platforms during build:

```
/__w/1/s/src/TorchSharp/GCHandleDeleter.cs(4,21): error CS1514: { expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
/__w/1/s/src/TorchSharp/GCHandleDeleter.cs(7,55): error CS1513: } expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
/__w/1/s/src/TorchSharp/TensorOrScalar.cs(4,21): error CS1514: { expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
/__w/1/s/src/TorchSharp/TensorOrScalar.cs(11,2): error CS1513: } expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
/__w/1/s/src/TorchSharp/GCHandleDeleter.cs(4,21): error CS1514: { expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
/__w/1/s/src/TorchSharp/GCHandleDeleter.cs(7,55): error CS1513: } expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
/__w/1/s/src/TorchSharp/TensorOrScalar.cs(4,21): error CS1514: { expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
/__w/1/s/src/TorchSharp/TensorOrScalar.cs(11,2): error CS1513: } expected [/__w/1/s/src/TorchSharp/TorchSharp.csproj]
```

**Comment by MovGP0** [comment]
> error CS1514: { expected
> error CS1513: } expected

This happens when [JetBrains Rider](https://www.jetbrains.com/rider/) automatically refactores to [File Scoped Namespaces](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces), while the compiler does not support C# 10.0. Maybe we should set the [LangVersion](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) element in the `*.csproj` files. Ie.

```xml
<Project>
 <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <!-- other Properties -->
 </PropertyGroup>

 <!-- other -->
</Project>
```

**Comment by NiklasGustafsson** [comment]
Good idea. Just added a PR with those changes.

**Comment by MovGP0** [comment]
Great! Will try to find some time next week to resolve the merge conflicts.

**Comment by NiklasGustafsson** [comment]
Also moved to .NET 6.0 instead of 5.0 while I was at it... :-)

**Comment by MovGP0** [comment]
I have now fixed the merge conflicts and the build issues.

**Pull request merged**
