### PR TITLE
Add `torch.stft()` and `torch.istft()`

### PR DESCRIPTION
**Pull request by kaiidams**
Depends on https://github.com/dotnet/TorchSharp/pull/604

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=605) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=605) before we can accept your contribution.<br/><br/>:x: kaiidams [sign now](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=605)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/TorchSharp?pullRequest=605) it.</sub>

**Comment by NiklasGustafsson** [comment]
@kaiidams -- I merged the 604 PR, so now there are conflicts.

**Comment by NiklasGustafsson** [comment]
@kaiidams, let me know when this is ready for review. The builds work, but it's still marked as "WIP," so I'll hold off.

**Review by NiklasGustafsson — APPROVED** [review]
Looks good to me.

**Comment by NiklasGustafsson** [comment]
@kaiidams -- now that you're a contributor, it would be great if you would introduce yourself in this thread: https://github.com/dotnet/TorchSharp/discussions/333

It's nice for the rest of us working on TorchSharp to know something about the people we collaborate with, and it's nice for people using TorchSharp to know a little bit about who is producing it. Completely voluntary, of course, but appreciated.

**Pull request merged**
